menu:
  #Archives: /archives
  # 黄金屋: /favourite
  # 时光机: /favourite/time.html
  # 幻想间: /favourite/image.html
  category: /category.html
  about: /aboutme.html
rss: /atom.xml
description:
social:
  weibo: 
  github: https://github.com/hellowupeng
  stack_overflow: 
  facebook: 
  twitter: 
  google_plus:

page_comment: true
logo: /images/avatar.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: 

google_analytics: 
baidu_tongji:
favicon: /images/avatar.jpg

#mathjax
mathjax: true

# 'Read more' button
excerpt_link: 继续阅读

# Footer message
site_license: <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享 署名-非商业性使用-相同方式共享 4.0 国际 许可协议</a>
thanks_message: thanks to <a href="https://pages.github.com/">GitHub Pages</a> for free hosting.

